# Generated by Django 4.1.7 on 2023-03-20 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCompte',
            fields=[
                ('id_av', models.AutoField(primary_key=True, serialize=False)),
                ('type_action', models.CharField(max_length=12)),
                ('date', models.DateField()),
                ('num_compte', models.CharField(max_length=5)),
                ('nom_client', models.CharField(max_length=255)),
                ('solde_anc', models.IntegerField()),
                ('solde_nouv', models.IntegerField()),
                ('utilisateur', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='AuditOperation',
            fields=[
                ('id_ao', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('num_cheque', models.CharField(max_length=5)),
                ('num_compte', models.CharField(max_length=5)),
                ('nom_client', models.CharField(max_length=255)),
                ('montant', models.IntegerField()),
                ('utilisateur', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='AuditRetrait',
            fields=[
                ('id_av', models.AutoField(primary_key=True, serialize=False)),
                ('type_action', models.CharField(max_length=12)),
                ('date', models.DateField()),
                ('num_ret', models.CharField(max_length=5)),
                ('num_compte', models.CharField(max_length=5)),
                ('nom_client', models.CharField(max_length=255)),
                ('montant_anc', models.IntegerField()),
                ('montant_nouv', models.IntegerField()),
                ('utilisateur', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='AuditVersement',
            fields=[
                ('id_av', models.AutoField(primary_key=True, serialize=False)),
                ('type_action', models.CharField(max_length=12)),
                ('date', models.DateField()),
                ('num_vers', models.CharField(max_length=5)),
                ('num_compte', models.CharField(max_length=5)),
                ('nom_client', models.CharField(max_length=255)),
                ('montant_anc', models.IntegerField()),
                ('montant_nouv', models.IntegerField()),
                ('utilisateur', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('num_compte', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nom_client', models.CharField(max_length=255)),
                ('solde', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=8, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('role', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Versement',
            fields=[
                ('num_vers', models.AutoField(primary_key=True, serialize=False)),
                ('num_cheque', models.CharField(max_length=5)),
                ('montant', models.IntegerField()),
                ('num_compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
            ],
        ),
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('num_ret', models.AutoField(primary_key=True, serialize=False)),
                ('num_cheque', models.CharField(max_length=5)),
                ('montant', models.IntegerField()),
                ('num_compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
            ],
        ),
    ]
