# Generated by Django 4.1.7 on 2023-04-18 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auditoperation_type_op'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditcompte',
            old_name='id_av',
            new_name='id_ac',
        ),
        migrations.RenameField(
            model_name='auditretrait',
            old_name='id_av',
            new_name='id_ar',
        ),
    ]
